### ISSUE TITLE
混合模式下菜单：多个目录打开重合

### ISSUE THREAD

**Issue by snksos** [suyuan32/simple-admin-backend-ui#19]
![image](https://user-images.githubusercontent.com/7006708/232962838-d8197088-a8b6-4dbc-b8de-99d1181fcefe.png)
![image](https://user-images.githubusercontent.com/7006708/232962916-96340f6b-ec39-4864-b329-9e8f3666caf4.png)

在你的演示站上：http://101.132.124.135/dashboard

**Comment by suyuan32** [comment]
看到了，的确是哈，会修复下

**Comment by suyuan32** [comment]
@snksos 演示站版本太旧，1.0版本已没有这个问题，可以使用 docker 先体验，近期会更新下演示网站

**Comment by suyuan32** [comment]
https://doc.ryansu.pro/zh/guide/basic-config/all_in_one.html

**Comment by suyuan32** [comment]
演示网站已更新
