### ISSUE TITLE
添加web的步骤文档期望可以更完善点

### ISSUE THREAD

**Issue by wensenz** [suyuan32/simple-admin-backend-ui#3]
文档地址：https://suyuan32.github.io/simple-admin-core/#/simple-admin/zh-cn/docs/quick_develop_example
<img width="697" alt="image" src="https://user-images.githubusercontent.com/10190672/192100060-a58bb2d0-21ff-4635-9590-5d606eddc818.png">
针对前端知识相对较弱的后端开发人员，期望可以有完整步骤

**Comment by suyuan32** [comment]
okk

**Comment by suyuan32** [comment]
@wensenz 新文档已提交

**Comment by wensenz** [comment]
效率真高

**Comment by suyuan32** [comment]
@wensenz QQ交流群 801043319
