### ISSUE TITLE
路由这么添加的？顺着文档没找到

### ISSUE THREAD

**Issue by wensenz** [suyuan32/simple-admin-backend-ui#4]
<img width="622" alt="image" src="https://user-images.githubusercontent.com/10190672/192523142-d9fa33e3-d8a0-4d84-9fa5-a2678030c3ef.png">

**Comment by suyuan32** [comment]
菜单设置

**Comment by wensenz** [comment]
需要先配置好， 才能访问？？

**Comment by suyuan32** [comment]
当然啦

**Comment by suyuan32** [comment]
添加菜单就行

**Comment by suyuan32** [comment]
可以选择不显示在侧边栏

**Comment by suyuan32** [comment]
https://vvbin.cn/doc-next/guide/router.html

**Comment by suyuan32** [comment]
参考 vben文档

**Comment by suyuan32** [comment]
https://vvbin.cn/doc-next/guide/auth.html#%E5%90%8E%E5%8F%B0%E5%8A%A8%E6%80%81%E8%8E%B7%E5%8F%96

**Comment by wensenz** [comment]
我好好看下vben的，理解理解

**Comment by suyuan32** [comment]
已经配置好了的，你就直接添加一个菜单就行，菜单和目录都录入路由中的

**Comment by wensenz** [comment]
还是调不太通
<img width="459" alt="image" src="https://user-images.githubusercontent.com/10190672/192536475-42a85b88-7934-4649-8663-923505d9d1c1.png">

<img width="745" alt="image" src="https://user-images.githubusercontent.com/10190672/192536592-78c61e17-032d-4710-9540-00400b7f008e.png">
<img width="872" alt="image" src="https://user-images.githubusercontent.com/10190672/192536936-2441fb71-8dda-40f1-8af5-a3020a06a467.png">

**Comment by wensenz** [comment]
<img width="788" alt="image" src="https://user-images.githubusercontent.com/10190672/192537574-a6de738a-b2ba-4fbb-9ea5-11c0be9f5a87.png">

**Comment by wensenz** [comment]
<img width="147" alt="image" src="https://user-images.githubusercontent.com/10190672/192538361-c0f4412f-4773-4158-a8ef-e4748790b40a.png">
好了，defHttp.post写成 defHttp.get了

**Comment by suyuan32** [comment]
看文档，现在是post请求了，之前的文档改了下

**Comment by suyuan32** [comment]
https://github.com/suyuan32/simple-admin-core/blob/example/api/api_desc/example.api

**Comment by suyuan32** [comment]
和错误消息类型
