### ISSUE TITLE
npm install之后npm serve都在mac运行不起来，依赖太多了

### ISSUE THREAD

**Issue by jsonMark** [suyuan32/simple-admin-backend-ui#5]
npm install之后npm serve都在mac运行不起来，依赖太多了

**Comment by jsonMark** [comment]
> npm install之后npm serve都在mac运行不起来，依赖太多了

pngquant failed to build, make sure that libpng-dev is installed

**Comment by jsonMark** [comment]
mac autoreconf: command not found

**Comment by suyuan32** [comment]
nodejs 需要 18.8.0 以上哦，16+不能运行

**Comment by suyuan32** [comment]
npm install -g yarn

**Comment by suyuan32** [comment]
使用yarn安装好一些

**Comment by suyuan32** [comment]
或者 pnpm

**Comment by jsonMark** [comment]
这个技术栈真新

**Comment by suyuan32** [comment]
用最新的，不然以后迁移升级麻烦

**Comment by wuxiao-ling197** [comment]
> 或者 pnpm

你好，我pnpm serve启动依赖报错 
![11](https://github.com/user-attachments/assets/5a1f26ea-6611-40bb-9bdb-4ed8ec94f912)
但是pnpm install 命令是执行成功的，要怎么解决这个问题呢
